name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  prettier:
    name: "Prettier"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies
        run: |
          corepack enable
          pnpm i

      - name: Log working directory
        run: echo $PWD

      - name: Log Prettier bin directory
        run: pnpm which prettier

      - name: Log Nx report
        run: pnpm nx report

      - name: Run Prettier via nx exec
        run: pnpm prettier
